name: Create Release

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     description: 'Version to release'
    #     required: false
    #     default: ''

env:
  IS_PRERELEASE: 'false'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Print version
        run: echo ${{ env.VERSION }}

      - name: Change prerelease status
        if: contains(env.VERSION, '-rc')
        run: echo "IS_PRERELEASE=true" >> $GITHUB_ENV
      
      - name: Print prerelease status
        run: echo ${{ env.IS_PRERELEASE }}

      - name: Read changelog for pre release build
        id: changelog_release
        uses: embedd-actions/read_changelog_action@v3
        with:
          changelogfile: 'CHANGELOG.md'
          tag: ${{ env.VERSION }}

      - name: Prepare release notes
        run: |
          echo "## [${{ needs.prepare.outputs.version}}] - $(date +'%Y-%m-%d')" >> Release_Notes.md 
          echo "" >> Release_Notes.md
          echo "## Изменения:" >> Release_Notes.md 
          echo "${{ steps.changelog_release.outputs.content }}" >> Release_Notes.md


      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "Release_Notes.md"
          allowUpdates: false
          prerelease: ${{ env.IS_PRERELEASE }}
          tag: ${{ env.VERSION }}
          commit: ${{ github.ref_name }}

